### PR TITLE
add script

### PR DESCRIPTION
**Pull request by hdm-dt-fb**
Hi @gtalarico , thought I add it here.
Not sure about the tools category though.(?)

### CODE REVIEW

**Comment by gtalarico** [comment]
That looks great. I would say 'Tools' is fine.
May I ask for a small change?

Could you remove rpw usage? 
I like to keep the snippets here rpw-free so people using api+python in other contexts 
(eg. dynamo) can benefit from it without having to understand rpw.

See other snippets for which doc/active view handlers to use:
http://www.revitapidocs.com/code/#Python_CreateDraftingView-py

**Comment by hdm-dt-fb** [comment]
Good! Sure, makes perfect sense to keep it generic. 
Will send an update tomorrow.

**Comment by hdm-dt-fb** [comment]
rpw dependency removed.

**Comment by gtalarico** [comment]
Beautiful, thanks @hdm-dt-fb !

**Pull request merged**
