### PR TITLE
added 'Snippets_PassCategoryAndClassAsVariables.cs' to 1-csharp-code

### PR DESCRIPTION
**Pull request by 2adicted**
A generic Revit API C# Snippet that shows how FilteredElementCollector .OfCategory() and .OfClass() can be used with variables instead of hard-coded values.

### CODE REVIEW

**Comment by gtalarico** [comment]
Thanks for sending the first csharp snippet!

**Comment by gtalarico** [comment]
Snippets are updating once a day on server reboot.
Should be up tomorrow

**Comment by 2adicted** [comment]
Exciting! Looking forward to sharing more content and contribute to your amazing effort!

**Comment by gtalarico** [comment]
http://www.revitapidocs.com/code/#CSharp_PassCategoryAndClassAsVariables-cs

**Pull request merged**
